# Not work because the products is generated by js
from flask import current_app

import requests, bs4, re, os

from selenium import webdriver
from selenium.webdriver.common.by import By

# Not work because the products are loaded by js script
def get_data_from_device_input_by_bs4(device_input: str) -> dict:
    result = {'error': None, 'device_name': None, 'price': None, 'device_img': None}

    url = f'https://cellphones.com.vn/catalogsearch/result?q={device_input}'
    res = requests.get(url)
    try:
        res.raise_for_status()
    except:
        result['error'] = 'Cannot reach the search result page.'
        return result
    
    soup = bs4.BeautifulSoup(res.text, 'lxml')

    nameElems = soup.select('#productListSearch > div.product-list-filter.is-flex.is-flex-wrap-wrap > div:nth-child(1) > div.product-info > a > div.product__name > h3')
    if len(nameElems) == 0:
        result['error'] = 'Cannot find any results.'
        return result
    result['device_name'] = nameElems[0].getText()

    priceElems = soup.select('#productListSearch > div.product-list-filter.is-flex.is-flex-wrap-wrap > div:nth-child(1) > div.product-info > a > div.block-box-price > div > p.product__price--show')
    if len(priceElems) == 0:
        result['error'] = 'Cannot get the price of this device.'
        return result
    result['price'] = int(re.sub("[.₫]", "", priceElems[0].getText()))

    imgElems = soup.select('#productListSearch > div.product-list-filter.is-flex.is-flex-wrap-wrap > div:nth-child(1) > div.product-info > a > div.product__image > img')
    if len(imgElems) != 0:
        imgurl = imgElems[0].get('src')
        imgres = requests.get(imgurl)
        file = open(os.path.join(current_app.root_path, 'static', os.path.basename(imgurl)), 'wb')
        for chunk in imgres.iter_content(100000):
            file.write(chunk)
        file.close()
        result['device_img'] = os.path.basename(imgurl)

    return result

# Use it
def get_data_from_device_input_by_selenium(device_input: str) -> dict:
    result = {'error': None, 'device_name': None, 'price': None, 'device_img': None}

    browser = webdriver.Chrome()
    url = f'https://cellphones.com.vn/catalogsearch/result?q={device_input}'
    browser.implicitly_wait(15)
    browser.get(url)

    try:
        nameElem = browser.find_element(By.CSS_SELECTOR, '#productListSearch > div.product-list-filter.is-flex.is-flex-wrap-wrap > div:nth-child(1) > div.product-info > a > div.product__name > h3')
        result['device_name'] = nameElem.text
    except:
        result['error'] = 'Cannot reach the search result page.'
        return result
    
    try:
        priceElem = browser.find_element(By.CSS_SELECTOR, '#productListSearch > div.product-list-filter.is-flex.is-flex-wrap-wrap > div:nth-child(1) > div.product-info > a > div.block-box-price > div > p.product__price--show')
        result['price'] = int(re.sub("[.₫]", "", priceElem.text))
    except:
        result['error'] = 'Cannot get the price of this device.'
        return result

    try:
        imgElem = browser.find_element(By.CSS_SELECTOR, '#productListSearch > div.product-list-filter.is-flex.is-flex-wrap-wrap > div:nth-child(1) > div.product-info > a > div.product__image > img')
        imgurl = imgElem.get_attribute('src')
        imgres = requests.get(imgurl)
        imgres.raise_for_status()
        file = open(os.path.join(current_app.root_path, 'static', os.path.basename(imgurl)), 'wb')
        for chunk in imgres.iter_content(100000):
            file.write(chunk)
        file.close()
        result['device_img'] = os.path.basename(imgurl)
    except:
        pass

    return result